---
title:    |
    | bumpsetscrapR:
    | An R package for scraping NCAA volleyball data
date: '`r format(Sys.time(), "%B %d, %Y")`'
author:  #Kayla Frisoli, Shannon Gallagher, and Amanda Luby
output:
  pdf_document:
    fig_caption: yes
    keep_tex: no
    number_sections: yes
header-includes:
  - \usepackage{hyperref}
bibliography: master.bib
---


Abstract
===============================================================================

We introduce the $\texttt{R}$ package $\texttt{bumpsetscrapR}$, which allows $\texttt{R}$ users and volleyball fans to easily interact with NCAA volleyball data. Currently this data is embedded within \href{http://stats.ncaa.org}{http://stats.ncaa.org} and is difficult to access, pull, analyze, and visualize. Other online volleyball data sources are proprietary or out of scope (i.e., they are not US college volleyball). This package allows users to analyze both men and woman's volleyball players as well as teams over time. Additionally, we introduce a $\texttt{R Shiny}$ application so users can summarize and visualize the scraped data. This app allows the programming novice to benefit from the data without having to learn the programming language $\texttt{R}$. Our end result is a combination \texttt{R} package / \texttt{R Shiny} app similar to that of past and current sports scraping tools such as hockey's \href{waronice.com}{waronice.com}, football's \texttt{R} package \texttt{nflscrapR}, and tennis's \texttt{R} package \texttt{deuce}. Notably, we maintain and improve upon these tools by maintaining current standards of reproducibility and by introducing a product that is easily interpretable by analysts, coaches, and players alike.

<!-- a "head to head" page -->
    
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning=FALSE)
knitr::opts_chunk$set(message = FALSE)

library(dplyr)
library(ggplot2)

## To change into library(courtsports)
devtools::load_all("../bumpsetscrapR")
```



<!-- # Introducing $\texttt{bumpsetscrapR}$ -->




<!-- # References {#sec:refs} -->

\footnotesize
